cate_cols: ['content_id', 'part']
cont_cols: ["answered_correctly_content",'rolling_avg_lagged_y']
seq_len: 100
CFG:
  learning_rate: 1.0e-3
  batch_size: 128
  num_workers: 4
  print_freq: 100
  test_freq: 1
  start_epoch: 0
  num_train_epochs: 5
  warmup_steps: 1
  max_grad_norm: 100
  gradient_accumulation_steps: 1
  weight_decay: 0.01
  dropout: 0.2
  emb_size: 20
  hidden_size: 20
  nlayers: 2
  nheads: 10
  seq_len: 20